/// 需要再当前工程下resources/base/profile/main_pages.json中进行注册才能正常路由,目前已经支持自动注册

export abstract class PagesConstant {
  public static Splash = "pages/Splash"
  public static Index = "pages/Index"
  public static Login = "pages/Login"
  public static Register = "pages/Register"
  public static MyCoin = "pages/MyCoin"
  public static Rank = "pages/Rank"
  public static SearchResult = "pages/SearchResult"
  public static MyCollect = "pages/MyCollect"
  public static Web = "pages/WebPage"
  public static Hotkey = "pages/HotKey"
  public static TreeDetail = "pages/TreeDetail"
  public static EnvironmentSwitch = "pages/EnvironmentSwitch"
  public static Setting = "pages/Setting"
  public static WebExample =  "pages/WebExample"
  public static WebComponent =  "pages/WebComponent"
  public static ObservedV2TestPage =  "pages/ObservedV2TestPage"
}