export class ListConfig {
  static readonly SPACE: number = 20
  static readonly CACHED_COUNT: number = 3
  static readonly DIVIDER_STROKE_WIDTH: number = 0.25
  static readonly DIVIDER_COLOR: string = '#2F2F2F'
  static readonly HORIZONTAL_PADDING: number = 3
}

export class CardStyle {
  static readonly BORDER_RADIUS: number = 12
  static readonly INNER_PADDING: number = 12
  static readonly SHADOW_RADIUS: number = 12
  static readonly TAG_BORDER_RADIUS: number = 4
  static readonly TAG_PADDING_LEFT: number = 6
  static readonly TAG_PADDING_RIGHT: number = 6
  static readonly TAG_PADDING_TOP: number = 2
  static readonly TAG_PADDING_BOTTOM: number = 2
  static readonly TAG_FONT_SIZE: number = 11
  static readonly SECTION_GAP: number = 8
}
